apiVersion: v1
kind: Service
metadata:
  name: log-foo
  labels:
    app: log-foo
    component: log-foo
    type: stream-ats
    spring-deployment-id: log-foo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: log-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log-foo
    component: log-foo
