apiVersion: v1
kind: Service
metadata:
  name: router-sink-kafka
  labels:
    app: router-sink-kafka
    type: stream-ats
    component: router-sink-kafka
    spring-deployment-id: router-sink
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: router-sink-kafka-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: router-sink-kafka 
    type: acceptance-tests
    component: router-sink-kafka
