apiVersion: v1
kind: Service
metadata:
  name: tcp
  labels:
    app: tcp
    component: tcp
    type: stream-ats
    spring-deployment-id: tcp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: tcp-port-1
    targetPort: 8080
    protocol: TCP
  - port: 1234
    name: tcp-port-2
    targetPort: 1234
    protocol: TCP
  selector:
    app: tcp
    component: tcp
