apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp
  labels:
    app: tcp
    type: stream-ats
    component: tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp
  template:
    metadata:
      labels:
        app: tcp
        component: tcp
    spec:
      containers:
      - name: tcp
        image: springcloudstream/tcp-source-kafka:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
            value: kafka-zk:2181
          - name: SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION
            value: tcp.out
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_REPLICATIONFACTOR
            value: "1"
          - name: TCP_PORT
            value: "1234"
          - name: LOGGING_FILE_NAME
            value: tcp-source.log
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: logfile,health,info
          - name: SPRING_CLOUD_STREAMAPP_SECURITY_ENABLED
            value: "false"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
