apiVersion: v1
kind: Service
metadata:
  name: jdbc
  labels:
    app: jdbc
    component: jdbc
    type: stream-ats
    spring-deployment-id: jdbc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: jdbc-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: jdbc
    component: jdbc
