apiVersion: v1
kind: Service
metadata:
  name: log-1
  labels:
    app: log-1
    component: log-1
    type: stream-ats
    spring-deployment-id: log-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: log-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log-1
    component: log-1
