apiVersion: v1
kind: Service
metadata:
  name: splitter-processor-kafka
  labels:
    app: splitter-processor-kafka
    type: stream-ats
    component: splitter-processor-kafka
    spring-deployment-id: splitter-processor
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: splitter-processor-kafka-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: splitter-processor-kafka 
    type: acceptance-tests
    component: splitter-processor-kafka
